/* This is stub file for gapi.client.acceleratedmobilepageurl definition tests */
/* IMPORTANT.
 * This file was automatically generated by https://github.com/harpojaeger/google-api-typings-generator.
 * Rather than editing it manually, you may find it useful to re-run the generator script.
 * In case of any problems, feel free to create issues on or make PRs against https://github.com/harpojaeger/google-api-typings-generator. Or just fork it yourself!
 **/

gapi.load('client', () => {
    // now we can use gapi.client

    gapi.client.load('acceleratedmobilepageurl', 'v1', () => {
        // now we can use gapi.client.acceleratedmobilepageurl

    });

});
